# Generated by Django 5.0.7 on 2024-07-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('ad_id', models.IntegerField(unique=True, verbose_name='ID объявления')),
                ('author', models.CharField(max_length=255, verbose_name='Автор объявления')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
